# Generated by Django 4.2.20 on 2025-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_stock_created_at_stock_features_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='forecast_days',
            field=models.IntegerField(default=7),
        ),
    ]
