# Generated by Django 4.2.20 on 2025-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_alter_stock_forecast_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mae',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
