# Generated by Django 4.2.20 on 2025-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_alter_stock_mae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='predicted_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='rmse',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
