services:
  - type: web
    name: stock-watchlist
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn stocksite.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "stock-watchlist-1.onrender.com"


